### ISSUE TITLE
Reorganizar estrutura de arquivos e pastas

### ISSUE THREAD

**Issue by hussani** [rafaelscbr/ibiblioteca#3]
Hoje não existe padrão dentro da sua estrutura de pastas, deixando basicamente todos os arquivos acessíveis ao usuário, já que a pasta raiz é a mesma utilizada para armazenar classes, configurações e até mesmo a versão inicial do seu banco de dados, tornando o projeto extremamente vulnerável a diversos ataques.

Organize as pastas da seguinte maneira:

**/** 
|- **config/** -> *armazenará configurações gerais da aplicação*
|- **public/** -> *será a pasta raiz do servidor, a única que um usuário terá acesso*
|- **src/** -> *pasta que armazenará os arquivos que trabalham com a lógica do sistema*

Esta organização de pastas tornará o sistema mais integro e manipulável.

**Comment by rafaelscbr** [comment]
Bacana a ideia, optei por aderir sua ideia de padronização, deixando o sistema mas seguro, optando por colocar pasta que contem arquivos de trabalham com a lógica do sistema e arquivos de configurações inacessível, tornando aplicação mais segura.
