### ISSUE TITLE
Definir melhor as camadas do projeto (MVC)

### ISSUE THREAD

**Issue by hussani** [rafaelscbr/ibiblioteca#5]
O projeto hoje possui diversas camadas em alguns mesmos arquivos.
Seria interessante se tivessemos pelo menos algumas camadas mais separadas, como a de processamento e armazenamento (model), a de entrada e saída de requisições (controller) e a de exibição (view).

Com isso seu código ficará mais fácil de compreender e de ser reutilizado.

**Comment by rafaelscbr** [comment]
Aplicada padrão
